# Analysis options for Tokyo Roulette Predictor
# Enforces strict code quality standards for Flutter/Dart
#
# Based on package:flutter_lints with additional custom rules
# for educational gambling simulator project
#
# This package, and the lints it includes, are licensed under the
# BSD 3-Clause License. You can see the license text at
# https://github.com/dart-lang/lints/blob/main/LICENSE

include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # ========================================
    # ERROR PREVENTION RULES
    # ========================================
    
    # Critical error rules
    avoid_empty_else: true
    avoid_print: true  # Use logging instead
    avoid_relative_lib_imports: true
    avoid_slow_async_io: true
    avoid_types_as_parameter_names: true
    cancel_subscriptions: true
    close_sinks: true
    control_flow_in_finally: true
    empty_statements: true
    hash_and_equals: true
    no_adjacent_strings_in_list: true
    no_duplicate_case_values: true
    test_types_in_equals: true
    throw_in_finally: true
    unnecessary_statements: true
    unrelated_type_equality_checks: true
    valid_regexps: true
    
    # Additional error prevention
    avoid_returning_null_for_void: true
    avoid_type_to_string: true
    literal_only_boolean_expressions: true
    no_logic_in_create_state: true
    prefer_void_to_null: true
    use_build_context_synchronously: true
    use_key_in_widget_constructors: true
    
    # ========================================
    # CODE STYLE RULES
    # ========================================
    
    # Naming conventions
    camel_case_extensions: true
    camel_case_types: true
    constant_identifier_names: true
    file_names: true
    non_constant_identifier_names: true
    
    # Return types and declarations
    always_declare_return_types: true
    annotate_overrides: true
    avoid_return_types_on_setters: true
    type_init_formals: true
    
    # Initialization and assignments
    avoid_init_to_null: true
    avoid_null_checks_in_equality_operators: true
    prefer_conditional_assignment: true
    prefer_initializing_formals: true
    unnecessary_null_aware_assignments: true
    unnecessary_null_in_if_null_operators: true
    
    # Async/await
    await_only_futures: true
    unawaited_futures: true
    
    # Collections
    prefer_collection_literals: true
    prefer_contains: true
    prefer_for_elements_to_map_fromIterable: true
    prefer_inlined_adds: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    prefer_iterable_whereType: true
    prefer_spread_collections: true
    
    # Strings
    prefer_adjacent_string_concatenation: true
    prefer_interpolation_to_compose_strings: true
    prefer_single_quotes: true
    unnecessary_brace_in_string_interps: true
    unnecessary_string_escapes: true
    unnecessary_string_interpolations: true
    use_string_buffers: true
    
    # Functions
    prefer_function_declarations_over_variables: true
    use_function_type_syntax_for_parameters: true
    use_rethrow_when_possible: true
    
    # Control flow
    curly_braces_in_flow_control_structures: true
    empty_catches: true
    prefer_if_null_operators: true
    prefer_is_not_operator: true
    
    # Constructors
    empty_constructor_bodies: true
    unnecessary_constructor_name: true
    
    # Classes and members
    library_names: true
    library_prefixes: true
    no_leading_underscores_for_library_prefixes: true
    no_leading_underscores_for_local_identifiers: true
    null_closures: true
    prefer_final_fields: true
    prefer_final_in_for_each: true
    prefer_final_locals: true
    recursive_getters: true
    unnecessary_getters_setters: true
    unnecessary_overrides: true
    unnecessary_this: true
    
    # ========================================
    # CODE CLEANUP RULES
    # ========================================
    
    unnecessary_const: true
    unnecessary_new: true
    unnecessary_nullable_for_final_variable_declarations: true
    unnecessary_parenthesis: true
    
    # ========================================
    # DOCUMENTATION RULES
    # ========================================
    
    slash_for_doc_comments: true
    comment_references: false  # Can be noisy with external references
    # public_member_api_docs: true  # Uncomment to require docs on all public APIs
    
    # ========================================
    # FLUTTER-SPECIFIC RULES
    # ========================================
    
    avoid_unnecessary_containers: true
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    sized_box_for_whitespace: true
    sort_child_properties_last: true
    use_colored_box: true
    use_decorated_box: true
    use_full_hex_values_for_flutter_colors: true
    
    # ========================================
    # SECURITY & BEST PRACTICES
    # ========================================
    
    avoid_web_libraries_in_flutter: true
    no_default_cases_in_switch: false  # Allow default cases
    prefer_typing_uninitialized_variables: true
    secure_pubspec_urls: true
    sort_pub_dependencies: true

analyzer:
  # Exclude generated and third-party code
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.gr.dart"
    - "**/generated_plugin_registrant.dart"
    - "lib/generated/**"
    - "build/**"
    - ".dart_tool/**"
  
  # Language configuration
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  
  # Error severity configuration
  errors:
    # Make certain warnings more visible
    todo: info
    fixme: info
    
    # Deprecation handling
    deprecated_member_use: warning
    deprecated_member_use_from_same_package: ignore
    
    # Strict on important issues
    invalid_annotation_target: error
    missing_required_param: error
    missing_return: error
    
    # Relax on less critical issues
    unused_import: warning
    unused_local_variable: warning
    dead_code: info
    
    # Security-related
    avoid_print: error  # Force use of proper logging
    
  # Strong mode settings
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
